POST http://localhost:3333/events
Content-Type:  application/json

{
  "title": 123,
  "details": "Evento 3.0",
  "maximunAttendees": 100
}

### 

POST http://localhost:3333/events/7b56821d-df05-495e-ad2d-292a699a2c16/attendees
Content-Type:  application/json

{
  "name": "Yitzhak Rodriguez",
  "email": "yitzhakrodriguez.0901@gmail.com"
}

###

GET http://localhost:3333/events/7b56821d-df05-495e-ad2d-292a699a2c16

###

GET http://localhost:3333/attendees/6/badge

### 
GET http://localhost:3333/attendees/6/check-in

###
GET http://localhost:3333/events/7b56821d-df05-495e-ad2d-292a699a2c16/attendees?query=Yitzhak
