POST http://localhost:3333/events
Content-Type:  application/json

{
  "title": 'nome do evento',
  "details": 'detalhe do evento',
  "maximunAttendees": capacidade maxima do evento
}

### 

POST http://localhost:3333/events/id-do-evento/attendees
Content-Type:  application/json

{
  "name": "nome a ser cadastrado no evento",
  "email": "email a ser cadastrado no evento"
}

###

GET http://localhost:3333/events/id-do-evento

###

GET http://localhost:3333/attendees/id-do-attendee/badge

### 

GET http://localhost:3333/attendees/id-do-attendee/check-in

###

GET http://localhost:3333/events/id-do-evento/attendees?query=nome-cadastrado-no-evento
