POST http://localhost:3333/events
Content-Type:  application/json

{
  "title": "Fullstack Event 2.0",
  "details": "Evento para programadores de todos os niveis",
  "maximunAttendees": 100
}

### 

POST http://localhost:3333/events/3a627cb6-29a6-4d42-9e5d-7aba4258946f/attendees
Content-Type:  application/json

{
  "name": "Yitzhak Rodriguez",
  "email": "yitzhakrodriguez.0901@gmail.com"
}

###

GET http://localhost:3333/events/3a627cb6-29a6-4d42-9e5d-7aba4258946f